export const database = {
  bio: {
    name: 'Per Johansson',
    tagline: 'Software Developer and Philosopher',
    email: 'per@email.com',
    github: 'https://github.com/PerraJ60',
    linkedin: 'https://www.linkedin.com/in/per-johansson-55823b108/',
  },
  positions: [
    {
      id: '1',
      title: 'Web Developer',
      company: 'QADB',
      startDate: '2018-11-01',
      endDate: null,
      employmentType: 'Project',
      location: 'Gothenburg Sweden',
      achievements: ['Development of website, using PHP framework'],
    },
    {
      id: '2',
      title: 'Programmer C++, FORTRAN',
      company: 'NKC',
      startDate: '2016-01-01',
      endDate: '2016-05-30',
      employmentType: 'Project',
      location: 'Gothenburg, Sweden',
      achievements: [
        'Converting an advanced FORTRAN calculation program for bearings components to C++, with visual representation in Microsoft Office Excel',
      ],
    },
    {
      id: '3',
      title: 'Developer C++, FORTRAN',
      company: 'System developer ITW Construction Products Inc. UK',
      startDate: '2010-01-15',
      endDate: '2015-12-31',
      employmentType: 'Full time',
      location: 'Gothenburg Sweden, Cornwall UK',
      achievements: [
        'Design, maintenance and development of software for roof/truss construction, aimed at the UK/Irish market. Advanced calculation programs originally developed in FORTRAN, with modules in C/C++. Work per distance Gothenburg/UK (via Skype, TeamViewer), periodically at location in UK',
      ],
    },
    {
      id: '4',
      title: 'Senior Software Developer',
      company: 'Capella AB',
      startDate: '2002-02-01',
      endDate: '2009-03-01',
      employmentType: 'Full time',
      location: 'Gothenburg, Sweden',
      achievements: [
        'Design and development of systems for document management. Electronic storage, e-archive, traceability etc. A web solution was also developed',
      ],
    },
    {
      id: '5',
      title: 'System developer',
      company: 'Consultec AB',
      startDate: '2001-05-01',
      endDate: '2002-02-01',
      employmentType: 'Full time',
      location: 'Gothenburg, Sweden',
      achievements: [
        'Development of calculation software for electric installation costs in buildings.',
      ],
    },
  ],
  products: [
    {
      id: '94200',
      name: 'SSW Regular Tagging Gun',
      image: 'images/products/94200.jpg',
      type: 'tool',
      qty: '5',
      price: '$119.45',
    },
    {
      id: '94201',
      name: 'All Steel Regular Tagging Gun Replacement Needles',
      image: 'images/products/94201.jpg',
      type: 'accessories',
      qty: '8',
      price: '$4.35',
    },
    {
      id: '94400',
      name: 'GSSW Economy Regular Tagging Gun',
      image: 'images/products/94400.jpg',
      type: 'tool',
      qty: '8',
      price: '$170.35',
    },
    {
      id: '94401',
      name: 'Economy Regular Tagging Needles',
      image: 'images/products/94401.jpg',
      type: 'accessories',
      qty: '2',
      price: '$5.45',
    },
    {
      id: '94202',
      name: 'All Steel Regular Tagging Gun Needles Without Blades',
      image: 'images/products/94202.jpg',
      type: 'accessories',
      qty: '3',
      price: '$2.90',
    },
    {
      id: '94113',
      name: 'Regular 2 inch Clear Tagging Fasteners',
      image: 'images/products/94113.jpg',
      type: 'accessories',
      qty: '11',
      price: '$3.45',
    },
    {
      id: '94104',
      name: 'Regular 2 inch Clear Hook Tagging Fasteners',
      image: 'images/products/94104.jpg',
      type: 'accessories',
      qty: '20',
      price: '$8.00',
    },
    {
      id: '94136',
      name: 'Regular 2 inch Black Clear Tagging Fasteners',
      image: 'images/products/94136.jpg',
      type: 'accessories',
      qty: '25',
      price: '$9.99',
    },
    {
      id: '94105',
      name: 'Regular 3 inch Red Tagging Fasteners',
      image: 'images/products/94105.jpg',
      type: 'accessories',
      qty: '29',
      price: '$11.99',
    },
  ],
};
